# Generated by Django 3.2.9 on 2021-11-12 18:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portifolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(max_length=255)),
                ('operacao', models.CharField(choices=[('VENDA', 'VENDA'), ('COMPRA', 'COMPRA')], default='COMPRA', max_length=10)),
                ('data', models.DateField()),
                ('quantidade', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('custos', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('daytrade', models.BooleanField(blank=True, null=True)),
                ('preco_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantidade_acumulada', models.PositiveIntegerField(blank=True, null=True)),
                ('lucro', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('portifolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='api.portifolio')),
            ],
            options={
                'ordering': ['ativo', 'data', 'id'],
            },
        ),
    ]
