# Generated by Django 3.2.9 on 2021-11-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_trade_daytrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='lucro',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='preco_medio',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='quantidade_acumulada',
        ),
    ]
